-- MySQL Script generated by MySQL Workbench
-- Sat Oct 21 12:08:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema despensa_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `despensa_app` ;

-- -----------------------------------------------------
-- Schema despensa_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `despensa_app` DEFAULT CHARACTER SET utf8 ;
USE `despensa_app` ;

-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT 'Nombre del producto',
  `price` DECIMAL(6,2) UNSIGNED NOT NULL COMMENT 'Precio del producto',
  `img_url` VARCHAR(250) NOT NULL COMMENT 'Url de la imagen del producto.',
  `calories` DECIMAL(6,2) UNSIGNED NOT NULL COMMENT 'Calorías del producto',
  `description` VARCHAR(255) NULL COMMENT 'Descripción del producto, notas, etc.',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Productos';


-- -----------------------------------------------------
-- Table `shopping_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopping_list` ;

CREATE TABLE IF NOT EXISTS `shopping_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `total_calories` DECIMAL(8,2) UNSIGNED NOT NULL COMMENT 'Total de calorías de todos los productos.',
  `total_price` DECIMAL(8,2) UNSIGNED NOT NULL COMMENT 'Precio total de los productos.',
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Lista de la compra';


-- -----------------------------------------------------
-- Table `unit_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unit_types` ;

CREATE TABLE IF NOT EXISTS `unit_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Tipo de unidad del producto (packs, bricks, botellas, kilos, gramos, latas)';


-- -----------------------------------------------------
-- Table `products_has_shopping_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products_has_shopping_list` ;

CREATE TABLE IF NOT EXISTS `products_has_shopping_list` (
  `product_id` INT NOT NULL,
  `shopping_list_id` INT NOT NULL,
  `unit_type_id` INT NOT NULL,
  `units_per_product` INT NOT NULL DEFAULT 1 COMMENT 'Unidades por producto.',
  `total_calories` DECIMAL(8,2) UNSIGNED NOT NULL COMMENT 'Total de calorías por unidad.',
  `total_price` DECIMAL(8,2) UNSIGNED NOT NULL COMMENT 'Precio total por unidad.',
  PRIMARY KEY (`product_id`, `shopping_list_id`, `unit_type_id`),
  CONSTRAINT `fk_products_has_shopping_list_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_shopping_list_shopping_list`
    FOREIGN KEY (`shopping_list_id`)
    REFERENCES `shopping_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_shopping_list_unit_types`
    FOREIGN KEY (`unit_type_id`)
    REFERENCES `unit_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Relación de productos y lista de la compra.';

CREATE INDEX `fk_products_has_shopping_list_shopping_list_id` ON `products_has_shopping_list` (`shopping_list_id` ASC) VISIBLE;

CREATE INDEX `fk_products_has_shopping_list_products_id` ON `products_has_shopping_list` (`product_id` ASC) VISIBLE;

CREATE INDEX `fk_products_has_shopping_list_unit_types_id` ON `products_has_shopping_list` (`unit_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `users` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `username_UNIQUE` ON `users` (`username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `settings` ;

CREATE TABLE IF NOT EXISTS `settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key_name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(250) NOT NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `key_name_UNIQUE` ON `settings` (`key_name` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
